### ISSUE TITLE
Does not support parenthesis

### ISSUE THREAD

**Issue by Bharadwaj-MP** [mikeringrose/simple-search-parser#4]
The parser does not work if string contains parenthesis. 
Example query:  (A or B) AND (C OR D)

<img width="725" alt="image" src="https://user-images.githubusercontent.com/106319017/184808728-48f07628-7da9-4608-b20e-bc79b21e2da3.png">

**Comment by trescube** [comment]
Did you run this against the open PR yet? That contains substantial improvements over the current state of master.

**Comment by Bharadwaj-MP** [comment]
Is it so? I will check with the open PR
